name: Keep Render Alive

on:
  schedule:
    - cron: "*/300 * * * *" # Runs every 15 minutes to keep Render Awake

jobs:
  keepAlive:
    runs-on: ubuntu-latest

    steps:
      - name: Send Keep-Alive Request
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://little-lemon-backend-3y4f.onrender.com/keep-alive
